// File-based note store. Every note is one JSON file in data/notes/ —
// human-readable, trivially backed up, no database to maintain.

import fs from "node:fs";
import path from "node:path";
import { syncNoteFile, archiveNoteFile, TRANSCRIPTS_DIR } from "./mdsync";

export const DATA_DIR = path.join(process.cwd(), "data");
export const NOTES_DIR = path.join(DATA_DIR, "notes");
export const MEDIA_DIR = path.join(DATA_DIR, "media");

// Note ids currently being processed by THIS server process. Kept on
// globalThis so dev-mode hot reloads don't lose it.
export const activeIds = (globalThis.__tdActive ??= new Set());

const PROCESSING_STATUSES = ["queued", "waiting", "fetching", "reading", "downloading", "transcribing", "summarizing"];

// Heartbeats let the dev server (4999) and the production service (3999),
// which share this data folder, see when the other is actively processing —
// so neither sweeps notes the other is still working on.
const HB_DIR = path.join(DATA_DIR, ".hb");
const HB_FRESH_MS = 3 * 60 * 1000;
const SWEEP_INTERVAL_MS = 5 * 60 * 1000;

function touchBeat() {
  try {
    fs.mkdirSync(HB_DIR, { recursive: true });
    fs.writeFileSync(path.join(HB_DIR, `${process.pid}.beat`), String(Date.now()));
  } catch {
    /* best effort */
  }
}

function clearBeat() {
  try {
    fs.rmSync(path.join(HB_DIR, `${process.pid}.beat`));
  } catch {
    /* already gone */
  }
}

export function markActive(id) {
  activeIds.add(id);
  touchBeat();
  if (!globalThis.__tdHb) {
    const t = setInterval(() => {
      if (activeIds.size) touchBeat();
    }, 60000);
    t.unref?.();
    globalThis.__tdHb = t;
  }
}

export function markDone(id) {
  activeIds.delete(id);
  if (!activeIds.size) clearBeat();
}

function foreignHeartbeatFresh() {
  try {
    for (const f of fs.readdirSync(HB_DIR)) {
      if (!f.endsWith(".beat") || f === `${process.pid}.beat`) continue;
      const p = path.join(HB_DIR, f);
      try {
        if (Date.now() - fs.statSync(p).mtimeMs < HB_FRESH_MS) return true;
        fs.rmSync(p); // stale beat from a dead process
      } catch {
        /* vanished */
      }
    }
  } catch {
    /* no heartbeat dir yet */
  }
  return false;
}

function ensureDirs() {
  fs.mkdirSync(NOTES_DIR, { recursive: true });
  fs.mkdirSync(MEDIA_DIR, { recursive: true });
}

// If a server died mid-pipeline (reboot, closed Terminal, crash), notes are
// left in a processing status forever. Any process may sweep them — but only
// when no OTHER process is actively working (fresh foreign heartbeat).
// Runs on first store access and then at most every 5 minutes.
function sweepInterrupted() {
  const now = Date.now();
  if (globalThis.__tdLastSweep && now - globalThis.__tdLastSweep < SWEEP_INTERVAL_MS) return;
  globalThis.__tdLastSweep = now;
  if (foreignHeartbeatFresh()) return;
  try {
    ensureDirs();
    for (const f of fs.readdirSync(NOTES_DIR)) {
      if (!f.endsWith(".json")) continue;
      const p = path.join(NOTES_DIR, f);
      try {
        const n = JSON.parse(fs.readFileSync(p, "utf8"));
        if (activeIds.has(n.id)) continue; // live in this process
        let changed = false;
        if (PROCESSING_STATUSES.includes(n.status)) {
          n.status = "error";
          n.error =
            "Processing was interrupted (the app restarted mid-run). Delete this note and add the link again.";
          changed = true;
        }
        if (n.researchStatus === "running") {
          n.researchStatus = null;
          changed = true;
        }
        if (n.translationStatus === "running") {
          n.translationStatus = null;
          changed = true;
        }
        // keep the ~/Documents/Transcripts mirror complete: write the .md
        // for any ready note that doesn't have one (or whose file vanished)
        if (n.status === "ready" && (n.transcript?.segments?.length || n.body)) {
          const fileGone = !n.mdPath || !fs.existsSync(path.join(TRANSCRIPTS_DIR, n.mdPath));
          if (fileGone) {
            try {
              const rel = syncNoteFile(n);
              if (rel && rel !== n.mdPath) {
                n.mdPath = rel;
                changed = true;
              }
            } catch {
              /* mirror is best-effort */
            }
          }
        }
        if (changed) saveNote(n); // atomic tmp+rename — never truncate primary data in place
      } catch {
        /* skip corrupt file */
      }
    }
  } catch {
    /* data dir not created yet */
  }
}

export function newId() {
  return (
    Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 8)
  );
}

function notePath(id) {
  // ids are generated by newId(); reject anything path-like just in case
  if (!/^[a-z0-9-]+$/i.test(id)) throw new Error("bad note id");
  return path.join(NOTES_DIR, `${id}.json`);
}

export function getNote(id) {
  sweepInterrupted();
  try {
    return JSON.parse(fs.readFileSync(notePath(id), "utf8"));
  } catch {
    return null;
  }
}

export function saveNote(note) {
  ensureDirs();
  const tmp = notePath(note.id) + ".tmp";
  fs.writeFileSync(tmp, JSON.stringify(note, null, 2));
  fs.renameSync(tmp, notePath(note.id));
  return note;
}

export function patchNote(id, patch) {
  const note = getNote(id);
  if (!note) return null;
  return saveNote({ ...note, ...patch });
}

export function listNotes() {
  sweepInterrupted();
  ensureDirs();
  const notes = [];
  for (const f of fs.readdirSync(NOTES_DIR)) {
    if (!f.endsWith(".json")) continue;
    try {
      const n = JSON.parse(fs.readFileSync(path.join(NOTES_DIR, f), "utf8"));
      // library list stays light — transcripts can be huge
      notes.push(lightEntry(n));
    } catch {
      /* skip corrupt file */
    }
  }
  notes.sort((a, b) => (b.createdAt || "").localeCompare(a.createdAt || ""));
  return notes;
}

// short browsable extract for library cards: the summary if there is one,
// otherwise the opening of the transcript
function deriveExcerpt(n) {
  let src = n.summary?.text || "";
  if (src) {
    src = src
      .split("\n")
      .filter((l) => !l.trim().startsWith("#"))
      .join(" ");
  } else if (n.body) {
    src = n.body;
  } else if (n.transcript?.segments?.length) {
    src = n.transcript.segments.slice(0, 6).map((s) => s.text).join(" ");
  }
  src = src
    .replace(/[*_`>|]/g, "")
    .replace(/\[(\d+:)?\d+:\d+\]/g, "")
    .replace(/\s+/g, " ")
    .trim();
  return src ? src.slice(0, 200) : null;
}

function lightEntry(n) {
  return {
    id: n.id,
    title: n.title,
    status: n.status,
    error: n.error,
    createdAt: n.createdAt,
    duration: n.duration,
    thumbnail: n.thumbnail,
    source: n.source,
    folder: n.folder || null,
    kind: n.kind || null,
    excerpt: deriveExcerpt(n),
    hasSummary: Boolean(n.summary),
  };
}

function snippetAround(text, q, span = 90) {
  const idx = text.toLowerCase().indexOf(q);
  if (idx < 0) return null;
  const start = Math.max(0, idx - Math.floor(span / 3));
  const cut = text.slice(start, start + span).trim();
  return (start > 0 ? "…" : "") + cut + (start + span < text.length ? "…" : "");
}

// Full-text search across titles, transcripts, and summaries.
// Scans the JSON files directly — fine at personal-library scale.
export function searchNotes(query) {
  sweepInterrupted();
  ensureDirs();
  const q = query.trim().toLowerCase();
  if (!q) return listNotes();
  const results = [];
  for (const f of fs.readdirSync(NOTES_DIR)) {
    if (!f.endsWith(".json")) continue;
    try {
      const n = JSON.parse(fs.readFileSync(path.join(NOTES_DIR, f), "utf8"));
      let snippet = null;
      let matched = (n.title || "").toLowerCase().includes(q);
      if (!matched && n.transcript?.segments) {
        for (const seg of n.transcript.segments) {
          if (seg.text.toLowerCase().includes(q)) {
            matched = true;
            snippet = { at: seg.start, text: snippetAround(seg.text, q) };
            break;
          }
        }
      }
      if (!matched && n.body?.toLowerCase().includes(q)) {
        matched = true;
        snippet = { at: null, text: snippetAround(n.body, q) };
      }
      if (!matched && n.summary?.text?.toLowerCase().includes(q)) {
        matched = true;
        snippet = { at: null, text: snippetAround(n.summary.text, q) };
      }
      if (matched) results.push({ ...lightEntry(n), snippet });
    } catch {
      /* skip corrupt file */
    }
  }
  results.sort((a, b) => (b.createdAt || "").localeCompare(a.createdAt || ""));
  return results;
}

// Folder management: rename moves every note (renaming onto an existing
// folder merges them); remove leaves the notes, just unsorted.
function bulkSetFolder(matchName, newValue) {
  ensureDirs();
  let count = 0;
  for (const f of fs.readdirSync(NOTES_DIR)) {
    if (!f.endsWith(".json")) continue;
    const p = path.join(NOTES_DIR, f);
    try {
      const n = JSON.parse(fs.readFileSync(p, "utf8"));
      if (n.folder === matchName) {
        n.folder = newValue;
        try {
          n.mdPath = syncNoteFile(n) || n.mdPath; // move the mirror file too
        } catch {
          /* mirror is best-effort */
        }
        saveNote(n); // atomic tmp+rename
        count++;
      }
    } catch {
      /* skip corrupt file */
    }
  }
  return count;
}

export function renameFolder(from, to) {
  return bulkSetFolder(from, to);
}

export function removeFolder(name) {
  return bulkSetFolder(name, null);
}

// Remove media/caption/transcript files that share the note id as prefix.
export function cleanupMedia(id) {
  try {
    for (const f of fs.readdirSync(MEDIA_DIR)) {
      if (f.startsWith(id)) fs.rmSync(path.join(MEDIA_DIR, f));
    }
  } catch {
    /* ignore */
  }
}

export function deleteNote(id) {
  const note = getNote(id);
  if (note) archiveNoteFile(note); // mirror .md moves to _history/, never lost
  try {
    fs.rmSync(notePath(id));
  } catch {
    /* already gone */
  }
  cleanupMedia(id);
}
